# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Setup AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        verbose: true
        arch: amd64
    - name: Dotnet AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore ./source/TescoStatementProcessorLambda
    - name: Build
      run: dotnet build ./source/TescoStatementProcessorLambda --no-restore 
    - name: Test
      run: dotnet test ./source/TescoStatementProcessorLambda.Tests --verbosity normal
    - name: Package 
      run: dotnet lambda package -pl ./source/TescoStatementProcessorLambda -c Release -pt zip -o package.zip
    - name: Deploy to S3
      run: aws s3 cp ./package.zip s3://moneymatters/lambda-packages/tesco_statement_handler/
    - name: Get package version from S3
      run: echo "TF_VAR_s3_object_version=$(aws s3api list-object-versions --bucket moneymatters --prefix lambda-packages/tesco_statement_handler/package.zip --query Versions[?IsLatest].VersionId --output text)" >> $GITHUB_ENV
    - uses: hashicorp/setup-terraform@v3
    - run: terraform -chdir=infrastructure init
    - name: Terraform Validate
      id: validate
      run: terraform -chdir=infrastructure validate
    - id: plan
      run: terraform -chdir=infrastructure plan
    - id: apply
      run: terraform -chdir=infrastructure apply -auto-approve